export enum QuestRequirementType {
  // 殺怪類
  KILL_SLIME = 'KILL_SLIME',
  KILL_GOBLIN_WARRIOR = 'KILL_GOBLIN_WARRIOR',
  KILL_FOREST_WOLF = 'KILL_FOREST_WOLF', // 新增
  KILL_CAVE_BAT = 'KILL_CAVE_BAT', // 新增

  // 採集類
  COLLECT_HERB = 'COLLECT_HERB',
  COLLECT_GOBLIN_EAR = 'COLLECT_GOBLIN_EAR',
  COLLECT_WOLF_PELT = 'COLLECT_WOLF_PELT', // 新增

  // 互動類
  TALK_TO_VILLAGE_CHIEF = 'TALK_TO_VILLAGE_CHIEF', // 新增

  // 其他
  REACH_LEVEL_10 = 'REACH_LEVEL_10',
}
